services:
  lightbox:
    build:
      context: .
    container_name: immich-folio
    restart: unless-stopped
    ports:
      - '7211:7211'
    env_file:
      - path: .env.local
        required: false
    volumes:
      - ./content:/app/content
